# Generated by Django 5.1.6 on 2025-02-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='PoratalUsers',
        ),
        migrations.AlterModelTable(
            name='poratalusers',
            table='db_portal_users',
        ),
    ]
