# Generated by Django 5.1.6 on 2025-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_poratalusers_portalusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalusers',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
