# Generated by Django 5.1.6 on 2025-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_portalusers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalusers',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
