# Generated by Django 5.1.6 on 2025-02-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_authentcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'View'), (2, 'Applied')])),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=10)),
                ('salary_range', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('date_of_posted', models.DateField()),
                ('notice_period', models.CharField(max_length=50)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_fk_users', to='api.portalusers')),
            ],
            options={
                'db_table': 'db_jobs',
            },
        ),
    ]
