# Generated by Django 5.1.6 on 2025-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobs_applicants_jobs_education_quaification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='is_applied',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='status',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applicants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
