# Generated by Django 5.1.6 on 2025-02-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_jobs_is_applied_remove_jobs_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'View'), (2, 'Applied')])),
                ('is_applied', models.BooleanField(default=False)),
                ('job_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_apply_fk_jobs', to='api.jobs')),
            ],
            options={
                'db_table': 'db_jobs_apply',
            },
        ),
    ]
