# Generated by Django 5.1.6 on 2025-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobsapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='openings',
            field=models.CharField(max_length=5),
        ),
    ]
